/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ravic
 */
public class DashboardView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        
        // Populate Dentist Dropdown
        cmbDentist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Select a Dentist", "Dr. Smith", "Dr. Perera", "Dr. Fernando" 
        }));
        
        // Populate Treatment Dropdown
        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Select a Treatment", "Cleaning", "Whitening", "Filling", "Root Canal", "Extraction" 
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardTpane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patientNameTxtField = new javax.swing.JTextField();
        contactNumberTxtField = new javax.swing.JTextField();
        cmbDentist = new javax.swing.JComboBox<>();
        cmbTreatment = new javax.swing.JComboBox<>();
        btnSaveAppointment = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlable11 = new javax.swing.JLabel();
        txtBillingPatientId = new javax.swing.JTextField();
        btnGenerateInvoice = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceiptArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(871, 432));

        DashboardTpane.setBackground(new java.awt.Color(0, 0, 0));
        DashboardTpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        DashboardTpane.setForeground(new java.awt.Color(255, 255, 255));
        DashboardTpane.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Patient Name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setText("Contact Number :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel3.setText("Treatment Type :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setText("Assigned Dentist :");

        patientNameTxtField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        patientNameTxtField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        patientNameTxtField.addActionListener(this::patientNameTxtFieldActionPerformed);

        contactNumberTxtField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        contactNumberTxtField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        contactNumberTxtField.addActionListener(this::contactNumberTxtFieldActionPerformed);

        cmbDentist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Dentist", "Dr. Smith ", "Dr. Perera", "Dr. Fernando" }));
        cmbDentist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cmbDentist.addActionListener(this::cmbDentistActionPerformed);

        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Treatment", "Cleaning", "Whitening", "Filling", "Root Canal", "Extraction" }));
        cmbTreatment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cmbTreatment.addActionListener(this::cmbTreatmentActionPerformed);

        btnSaveAppointment.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveAppointment.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnSaveAppointment.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAppointment.setText("Save Appointment");
        btnSaveAppointment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSaveAppointment.addActionListener(this::btnSaveAppointmentActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contactNumberTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(patientNameTxtField)
                            .addComponent(cmbDentist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTreatment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnSaveAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contactNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnSaveAppointment)
                .addGap(55, 55, 55))
        );

        DashboardTpane.addTab("Register Appointment", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("Search Patient");

        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Search......");
        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnViewAll.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAll.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnViewAll.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAll.setText("VeiwAll");
        btnViewAll.addActionListener(this::btnViewAllActionPerformed);

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Contact", "Dentist", "Treatment"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewAll))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnViewAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        DashboardTpane.addTab("Search Records", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setText("Billing & Receipts");

        jlable11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jlable11.setText("Enter Patient ID :");

        txtBillingPatientId.setText("Id here....");
        txtBillingPatientId.addActionListener(this::txtBillingPatientIdActionPerformed);

        btnGenerateInvoice.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerateInvoice.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnGenerateInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateInvoice.setText("Genorate");
        btnGenerateInvoice.addActionListener(this::btnGenerateInvoiceActionPerformed);

        txtReceiptArea.setEditable(false);
        txtReceiptArea.setColumns(20);
        txtReceiptArea.setRows(5);
        jScrollPane2.setViewportView(txtReceiptArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerateInvoice)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(jLabel6))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jlable11)
                                    .addGap(56, 56, 56)
                                    .addComponent(txtBillingPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlable11)
                    .addComponent(txtBillingPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerateInvoice)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        DashboardTpane.addTab("Billing & Receipts", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardTpane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DashboardTpane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtFieldActionPerformed

    private void contactNumberTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTxtFieldActionPerformed

    private void cmbDentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDentistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDentistActionPerformed

    private void cmbTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTreatmentActionPerformed

    private void btnSaveAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAppointmentActionPerformed
        // 1. Gather the data from the fields
        String patientName = patientNameTxtField.getText().trim();
        String contactNumber = contactNumberTxtField.getText().trim();
        String dentist = cmbDentist.getSelectedItem().toString();
        String treatment = cmbTreatment.getSelectedItem().toString();

        // 2. Basic UI Validation (Ensure fields aren't empty)
        if (patientName.isEmpty() || contactNumber.isEmpty() || 
            dentist.equals("Select a Dentist") || treatment.equals("Select a Treatment")) {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill out all fields before saving.", 
                "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Connect to the Controller (We will create this next!)
        controller.AppointmentController apptCtrl = new controller.AppointmentController();
        String result = apptCtrl.registerAppointment(patientName, contactNumber, dentist, treatment);

        // 4. Show Success or Error
        if (result.equals("SUCCESS")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment Saved Successfully!");
            
            // Clear the fields for the next patient
            patientNameTxtField.setText("");
            contactNumberTxtField.setText("");
            cmbDentist.setSelectedIndex(0);
            cmbTreatment.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving appointment: " + result);
        }
    }//GEN-LAST:event_btnSaveAppointmentActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // Clear the search box
        txtSearch.setText("");
        
        // Passing an empty string triggers the controller to fetch all records
        controller.SearchController searchCtrl = new controller.SearchController();
        tblAppointments.setModel(searchCtrl.getAppointmentTable(""));
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Capture what the user typed
        String searchTerm = txtSearch.getText().trim();
        
        // Pass to controller and update the table
        controller.SearchController searchCtrl = new controller.SearchController();
        tblAppointments.setModel(searchCtrl.getAppointmentTable(searchTerm));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtBillingPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillingPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBillingPatientIdActionPerformed

    private void btnGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane DashboardTpane;
    private javax.swing.JButton btnGenerateInvoice;
    private javax.swing.JButton btnSaveAppointment;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbTreatment;
    private javax.swing.JTextField contactNumberTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlable11;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtBillingPatientId;
    private javax.swing.JTextArea txtReceiptArea;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
