/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ravic
 */
public class DentistDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DentistDashboard.class.getName());
    private String loggedInDentist;

    // Default constructor (leave this alone so NetBeans doesn't complain)
    public DentistDashboard() {
        initComponents();
    }

    // 2. Add this NEW constructor right below it
    public DentistDashboard(String username) {
        initComponents();
        this.loggedInDentist = username; 
        
        // Optional: Change the window title to welcome them!
        this.setTitle("Dashboard - " + username);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLaunchSchedule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(871, 432));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setText("DentistWebService");

        btnLaunchSchedule.setBackground(new java.awt.Color(0, 0, 0));
        btnLaunchSchedule.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLaunchSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnLaunchSchedule.setText("Launch Web Schedule");
        btnLaunchSchedule.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        btnLaunchSchedule.addActionListener(this::btnLaunchScheduleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(btnLaunchSchedule)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addComponent(btnLaunchSchedule)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaunchScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchScheduleActionPerformed

        if (this.loggedInDentist == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No dentist logged in.");
            return;
        }

        controller.DentistWebService webService = new controller.DentistWebService();
        webService.startServer(this.loggedInDentist);
        
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("http://localhost:8080/schedule"));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error opening browser: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLaunchScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DentistDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaunchSchedule;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
